<?php

/**
 * @file
 * Adds dropzone.js field type to the webforms module.
 */

/**
 * Implements hook_theme().
 */
function webform_dropzonejs_theme() {
  $info = [
    'webform_element_dropzonejs' => [
      'variables' => [
        'element' => [],
        'value' => NULL,
        'webform_submission' => NULL,
        'options' => [],
        'file' => NULL,
      ],
    ],
  ];

  return $info;
}

/**
 * Preprocesses "webform_element_dropzonejs".
 */
function template_preprocess_webform_element_dropzonejs(array &$variables) {
  template_preprocess_webform_element_managed_file($variables);
}
